export const mbtiTypes =  {
        INFJ: { name: "INFJ",
                 functions: ["Ni", "Fe", "Ti", "Se", "Ne", "Fi", "Te", "Si"],
                pic: "/assets/mbti-char-imgs/infj.png",
                descr: "Os INFJ...",
            },
  INTJ: {       name: "INTJ",
         functions: ["Ni", "Te", "Fi", "Se","Ne", "Ti", "Fe", "Si"],
  pic: "/assets/mbti-char-imgs/png-transparent-architect-intj-myers-briggs-type-indicator-personality-career-rationality-purple-violet-architect.png",
  descr: "Os INTJ...",
   },
  ENFP: {       name: "ENFP", 
        functions: ["Ne", "Fi", "Te", "Si","Ni", "Fe", "Ti", "Se"],
  pic: "/assets/mbti-char-imgs/czM6Ly9tZWRpYS1wcml2YXRlLmNhbnZhLmNvbS8wY290QS9NQUZ1aUIwY290QS8xL3AucG5n.png",
  descr: "Os ENFP...",
   },
  ISTJ: {       name: "ISTJ",
         functions: ["Si", "Te", "Fi", "Ne", "Se", "Ti", "Fe", "Ni"],
  pic: "/assets/mbti-char-imgs/istj.png",
  descr: "Os ISTJ...",
  },
  ESTJ: {       name: "ESTJ",
        functions: ["Te", "Si", "Ne", "Fi", "Ti", "Se", "Ni", "Fe"],
  pic: "/assets/mbti-char-imgs/estj.webp",
  descr: "Os ESTJ...",
   },
  ISFJ: {       name: "ISFJ",
        functions: ["Si", "Fe", "Ti", "Ne", "Se", "Fi", "Te", "Ni"],
  pic: "/assets/mbti-char-imgs/istj.png",
  descr: "Os ISFJ...",
   },
  ESFP: {       name: "ESFP", 
        functions: ["Se", "Fi", "Te", "Ni", "Si", "Fe", "Ti", "Ne"],
  pic: "/assets/mbti-char-imgs/esfp.png",
  descr: "Os ESFP...",
   },
  ISFP: {       name: "ISFP", 
        functions: ["Fi", "Se", "Ni", "Te", "Fe", "Si", "Ne", "Ti"],
  pic: "/assets/mbti-char-imgs/esfp.png",
  descr: "Os ISFP...",
   },
  INTP: {       name: "INTP",
        functions: ["Ti", "Ne", "Si", "Fe", "Te", "Ni", "Se", "Fi"],
  pic: "/assets/mbti-char-imgs/intp.png",
  descr: "Os INTP...", },
  ENTP: {       name: "ENTP", 
        functions: ["Ne", "Ti", "Fe", "Si","Ne", "Te", "Fi", "Se"],
  pic: "/assets/mbti-char-imgs/intp.png",
  descr: "Os ENTP...",
  },
  ENTJ: { name: "ENTJ",
        functions: ["Te", "Ni", "Se", "Fi", "Ti", "Ne", "Se", "Fe"],
  pic: "/assets/mbti-char-imgs/entj.png",
  descr: "Os ENTJ...",
   },
  INFP: {       name: "INFP",
        functions: ["Fi", "Ne", "Si", "Te", "Fe", "Ni", "Se", "Ti"],
  pic: "/assets/mbti-char-imgs/infp.png",
  descr: "Os INFP...",
   },
  ENFJ: {       name: "ENFJ", 
        functions: ["Fe", "Ni", "Se", "Ti", "Fi", "Ne", "Si", "Te"],
  pic: "/assets/mbti-char-imgs/enfj.png",
  descr: "Os eNFJ...",
  },
  ESTP: {       name: "ESTP",
        functions: ["Se", "Ti", "Fe", "Ni", "Si", "Te", "Fi", "Ne"],
  pic: "/assets/mbti-char-imgs/esfp.png",
  descr: "Os ESTP...",
   },
  ISTP: {       name: "ISTP", 
        functions: ["Ti", "Se", "Ni", "Fe", "Te", "Si", "Ne", "Fi"],
  pic: "/assets/mbti-char-imgs/esfp.png",
  descr: "Os ISTP...",
 },
  ESFJ: { name: "ESFJ",
        functions: ["Fe", "Si", "Ne", "Ti", "Fi", "Se", "Ni", "Te"],
  pic: "/assets/mbti-char-imgs/istj.png",
  descr: "Os ESFJ...",
   },
  }

  